.TH "IniFormat" 3 "Sun Apr 15 2018" "libconfini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IniFormat \- 24-bit bitfield representing a unique format of an INI file (INI dialect) – \fCsizeof(IniFormat)\fP should be \fC3\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <confini\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBdelimiter_symbol\fP: 8"
.br
.ti -1c
.RI "unsigned char \fBsemicolon_marker\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBhash_marker\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBmultiline_nodes\fP: 2"
.br
.ti -1c
.RI "unsigned char \fBcase_sensitive\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBno_spaces_in_names\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBno_single_quotes\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBno_double_quotes\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBimplicit_is_not_empty\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBdo_not_collapse_values\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBpreserve_empty_quotes\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBno_disabled_after_space\fP: 1"
.br
.ti -1c
.RI "unsigned char \fBdisabled_can_be_implicit\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
24-bit bitfield representing a unique format of an INI file (INI dialect) – \fCsizeof(IniFormat)\fP should be \fC3\fP 

Structure of the bitfield:
.PP
.IP "\(bu" 2
Bits 1-18: INI syntax
.IP "\(bu" 2
Bits 19-21: INI semantics
.IP "\(bu" 2
Bits 22-23: human syntax (disabled entries)
.IP "\(bu" 2
Bit 24: not used 
.PP

.SH "Field Documentation"
.PP 
.SS "IniFormat::case_sensitive"
If set to \fC1\fP, string comparisons will always be performed case-sensitive 
.SS "IniFormat::delimiter_symbol"
The symbol to be used as delimiter; if set to \fC0\fP, any space is delimiter (\fC/(?:\\\\(?:\\n\\r?|\\r\\n?)|[\\t \\v\\f])+/\fP) 
.SS "IniFormat::disabled_can_be_implicit"
If set to \fC1\fP, comments non containing a delimiter symbol will not be parsed as disabled implicit keys, but as simple comments 
.SS "IniFormat::do_not_collapse_values"
If set to \fC1\fP, sequences of more than one space in values (\fC/\\s{2,}/\fP) will not be collapsed 
.SS "IniFormat::hash_marker"
The rule of the hash character (use enum \fC\fBIniCommentMarker\fP\fP for this) 
.SS "IniFormat::implicit_is_not_empty"
If set to \fC1\fP, implicit keys (see \fBLibrary Functions Manual\fP) will always be dispatched using the values of the global variables \fC\fBINI_GLOBAL_IMPLICIT_VALUE\fP\fP and \fC\fBINI_GLOBAL_IMPLICIT_V_LEN\fP\fP for the fields \fC\fBIniDispatch::value\fP\fP and to \fC\fBIniDispatch::v_len\fP\fP respectively; if set to \fC0\fP, implicit keys will be considered to be empty keys 
.SS "IniFormat::multiline_nodes"
Defines which class of entries are allowed to be multi-line (use enum \fC\fBIniMultiline\fP\fP for this) 
.SS "IniFormat::no_disabled_after_space"
If set to \fC1\fP, prevents that what follows \fC/(?:^|\\s+)[#;]\\s/\fP be parsed as a disabled entry 
.SS "IniFormat::no_double_quotes"
If set to \fC1\fP, the double-quote character (\fC"\fP) will be considered as a normal character 
.SS "IniFormat::no_single_quotes"
If set to \fC1\fP, the single-quote character (\fC'\fP) will be considered as a normal character 
.SS "IniFormat::no_spaces_in_names"
If set to \fC1\fP, key and section names containing spaces will be rendered as \fC\fBINI_UNKNOWN\fP\fP\&. Note that setting \fC\fBIniFormat::delimiter_symbol\fP\fP to \fCINI_ANY_SPACE\fP will not automatically set this option to \fC1\fP (spaces will still be allowed in section names)\&. 
.SS "IniFormat::preserve_empty_quotes"
If set to \fC1\fP and if single/double quotes are metacharacters ensures that empty strings enclosed between quotes (\fC''\fP or \fC''\fP) will not be collapsed together with spaces\&. 
.SS "IniFormat::semicolon_marker"
The rule of the semicolon character (use enum \fC\fBIniCommentMarker\fP\fP for this) 

.SH "Author"
.PP 
Generated automatically by Doxygen for libconfini from the source code\&.
