.TH "IniStatistics" 3 "Mon Oct 26 2020" "libconfini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IniStatistics \- Global statistics about an INI file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <confini\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBIniFormat\fP \fBformat\fP"
.br
.ti -1c
.RI "const size_t \fBbytes\fP"
.br
.ti -1c
.RI "const size_t \fBmembers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Global statistics about an INI file\&. 
.SH "Field Documentation"
.PP 
.SS "IniStatistics::bytes"
The size of the parsed file in bytes 
.SS "IniStatistics::format"
The format of the INI file (see \fBIniFormat\fP) 
.SS "IniStatistics::members"
The size of the parsed file in number of members (nodes) – this number always equals the number of dispatches that will be produced by \fBload_ini_file()\fP, \fBload_ini_path()\fP or \fBstrip_ini_cache()\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for libconfini from the source code\&.
