.TH "libconfini" 3 "Thu Oct 6 2016" "libconfini" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libconfini \- Library Functions Manual 

.SH "OVERVIEW"
.PP
.PP
\fBlibconfini\fP is a simple INI parsing library with the ability to read disabled entries (i\&.e\&., commented lines)\&. \fBlibconfini\fP does not store the data read from an INI file, but rather dispatches it, formatted, to a custom listener\&.
.PP
Unfortunately this manual has not been written yet\&. You can find a partially self-documented sample usage of \fBlibconfini\fP under /usr/share/doc/libconfini/examples/\&. Or type \fBman \fBconfini\&.h\fP\fP for an overview of the API\&. 
